# https://aka.ms/yaml

jobs:
  - job: build_lint_test_push
    displayName: 'Build, Lint, Test, & Push'

    pool:
      vmImage: 'ubuntu-18.04'

    variables:
      BASE_CHANGED: 'True'
      VENV_CHANGED: 'True'
      BASE_PULL: 'False'
      VENV_PULL: 'False'

    steps:
      - template: ci/build.yml
      - template: ci/setup.yml
      - template: ci/lint.yml
      - template: ci/test.yml
      - template: ci/push.yml
